defaults: &defaults
  http://www.w3.org/2001/XMLSchema#string: 
    typed: :to_s
    literal: :to_s
  http://www.w3.org/2001/XMLSchema#boolean:
    typed: :to_bool
    literal: :to_s
  http://www.w3.org/2001/XMLSchema#dateTime:
    typed: :to_time_with_default
    literal: :iso8601
  http://www.w3.org/2001/XMLSchema#integer: 
    typed: :to_i
    literal: :to_s
  http://www.w3.org/2001/XMLSchema#positveInteger: 
    typed: :to_i 
    literal: :to_s

development:
  <<: *defaults

production: 
  <<: *defaults
  
test: 
  <<: *defaults